//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.07 at 11:50:54 PM CET 
//


package org.example.entity.bookings;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import org.example.entity.hotel.Hotel;
import org.example.entity.room.Room;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="booking" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://example.com/hotel-booking/hotel}hotel"/&gt;
 *                   &lt;element ref="{http://example.com/hotel-booking/room}room"/&gt;
 *                   &lt;element name="clientName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="status"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Підтверджено"/&gt;
 *                         &lt;enumeration value="Скасовано"/&gt;
 *                         &lt;enumeration value="В очікуванні"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="guestCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "booking"
})
@XmlRootElement(name = "bookings")
public class Bookings {

    @XmlElement(required = true)
    protected List<Booking> booking;

    /**
     * Gets the value of the booking property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore, any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the booking property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBooking().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Booking }
     * 
     * 
     */
    public List<Booking> getBooking() {
        if (booking == null) {
            booking = new ArrayList<Booking>();
        }
        return this.booking;
    }

    public void setBooking(List<Booking> booking) {
        this.booking = booking;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Bookings{");
        if (booking != null) {
            for (Booking b : booking) {
                sb.append("\n\tBooking{")
                        .append("id=").append(b.getId())
                        .append(", hotel=").append(b.getHotel())
                        .append(", room=").append(b.getRoom())
                        .append(", clientName='").append(b.getClientName()).append('\'')
                        .append(", startDate=").append(b.getStartDate())
                        .append(", endDate=").append(b.getEndDate())
                        .append(", status='").append(b.getStatus()).append('\'')
                        .append(", guestCount=").append(b.getGuestCount())
                        .append("}");
            }
        }
        sb.append("\n}");
        return sb.toString();
    }
}
