//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.07 at 11:50:54 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://example.com/hotel-booking/hotel", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.entity.hotel;
